### PR TITLE
 add CMake support

### PR DESCRIPTION
**Pull request by xueliu**
In this patch CMake is introduced

Signed-off-by: Xue Liu <liuxuenetmail@gmail.com>

### CODE REVIEW

**Comment by brainstorm** [comment]
You are awesome @xueliu, thanks for this :)

**Comment by xueliu** [comment]
Please have a try to check whether

**Comment by xueliu** [comment]
> You are awesome @xueliu, thanks for this :)

Thanks. Please have a try to check whether it is working.

**Review by brainstorm — CHANGES_REQUESTED** [review]
@xueliu Everything builds like a charm, although some object conventions are a bit... unconventional:

```
$ find . -iname *.c.o
./libloragw/CMakeFiles/test_loragw_cal.dir/tst/test_loragw_cal.c.o
./libloragw/CMakeFiles/test_loragw_hal.dir/tst/test_loragw_hal.c.o
./libloragw/CMakeFiles/test_loragw_reg.dir/tst/test_loragw_reg.c.o
./libloragw/CMakeFiles/loragw.dir/src/loragw_aux.c.o
./libloragw/CMakeFiles/loragw.dir/src/loragw_radio.c.o
./libloragw/CMakeFiles/loragw.dir/src/loragw_reg.c.o
```

Typically the objects should be named `.o`, not `.c.o`? Just that tiny detail, the rest is great work indeed 👍

**Comment by brainstorm** [comment]
@mcoracin @Lora-net, for context, this PR is relevant and useful to properly package/include this software in OpenWRT:

https://github.com/openwrt/packages/pull/8264#issuecomment-465978336

Please consider merging this work if you want higher uptake/use of this Semtech software stack :)

**Comment by xueliu** [comment]
> @xueliu Everything builds like a charm, although some object conventions are a bit... unconventional:
> 
> ```
> $ find . -iname *.c.o
> ./libloragw/CMakeFiles/test_loragw_cal.dir/tst/test_loragw_cal.c.o
> ./libloragw/CMakeFiles/test_loragw_hal.dir/tst/test_loragw_hal.c.o
> ./libloragw/CMakeFiles/test_loragw_reg.dir/tst/test_loragw_reg.c.o
> ./libloragw/CMakeFiles/loragw.dir/src/loragw_aux.c.o
> ./libloragw/CMakeFiles/loragw.dir/src/loragw_radio.c.o
> ./libloragw/CMakeFiles/loragw.dir/src/loragw_reg.c.o
> ```
> Typically the objects should be named `.o`, not `.c.o`? Just that tiny detail, the rest is great work indeed 👍

I think CMake use this name convention internally. We don't need to take care of it.

**Pull request closed without merging**
